### ISSUE TITLE
umu-launcher

### ISSUE THREAD

**Issue by Pednick** [Cloudef/elden-proton#10]
Does this work in:
https://github.com/Open-Wine-Components/umu-launcher

**Comment by Cloudef** [comment]
`bash elden-proton.bash whatever-command-line-you-use-to-launch-elden-ring`
Might work but not guaranteed, you might have to set `STEAM_RUNTIME` variable, `ER_PATH` lets you control Elden Ring installation location.

**Comment by Pednick** [comment]
> `bash elden-proton.bash whatever-command-line-you-use-to-launch-elden-ring` Might work but not guaranteed, you might have to set `STEAM_RUNTIME` variable, `ER_PATH` lets you control Elden Ring installation location.

Ok, I'll give it a try, Thank You.

**Comment by Cloudef** [comment]
For reference, this is all that elden-proton does before launching the game:
https://github.com/Cloudef/elden-proton/blob/master/elden-proton.bash#L253-L269

**Comment by Pednick** [comment]
> For reference, this is all that elden-proton does before launching the game: https://github.com/Cloudef/elden-proton/blob/master/elden-proton.bash#L253-L269

So it would be something like this?
STEAM_PATH="${STEAM_PATH:-"$HOME"/.local/share/Steam/compatibilitytools.d/GE-Proton9-4}"
ER_PATH="${ER_PATH:-"$HOME"/Games/umu/umu-ELDENRING/drive_c/Games/'ELDEN RING'/Game}"

**Comment by Cloudef** [comment]
No need to set STEAM_PATH, it's only used for setting ER_PATH unless you set ER_PATH yourself.
Based on umu's README it would look like this for you:
```bash
ER_PATH="$HOME"/Games/umu/umu-ELDENRING/drive_c/Games/'ELDEN RING'/Game \
WINEPREFIX=<wine-prefix-path> \
GAMEID=<umu-id> \
PROTONPATH="$HOME"/.local/share/Steam/compatibilitytools.d/GE-Proton9-4 \
bash elden-proton.bash umu-run "$ER_PATH"/eldenring.exe
```

**Comment by Pednick** [comment]
> No need to set STEAM_PATH, it's only used for setting ER_PATH unless you set ER_PATH yourself. Based on umu's README it would look like this for you:
> 
> ```shell
> ER_PATH="$HOME"/Games/umu/umu-ELDENRING/drive_c/Games/'ELDEN RING'/Game \
> WINEPREFIX=<wine-prefix-path> \
> GAMEID=<umu-id> \
> PROTONPATH="$HOME"/.local/share/Steam/compatibilitytools.d/GE-Proton9-4 \
> bash elden-proton.bash umu-run "$ER_PATH"/eldenring.exe
> ```

Oh ok, I'm using umu sourced based so I have it like this:
GAMEID=umu-ELDENRING PROTONPATH=GE-Proton9-4 umu-run winecfg
GAMEID=umu-ELDENRING PROTONPATH=GE-Proton9-4 umu-run explorer

GAMEID=umu-ELDENRING PROTONPATH=GE-Proton9-4 WINEDLLOVERRIDES="dinput8.dll=n,b" umu-run /home/user/Games/umu/umu-ELDENRING/drive_c/Games/'ELDEN RING'/Game/eldenring.exe

I used "user" on here for security reasons.

**Comment by Cloudef** [comment]
> GAMEID=umu-ELDENRING PROTONPATH=GE-Proton9-4 WINEDLLOVERRIDES="dinput8.dll=n,b" umu-run /home/user/Games/umu/umu-ELDENRING/drive_c/Games/'ELDEN RING'/Game/eldenring.exe

You should be able to use this line, you can drop WINEDLLOVERRIDES and prefix the umu-run with `bash elden-proton.bash`

**Comment by Pednick** [comment]
> > GAMEID=umu-ELDENRING PROTONPATH=GE-Proton9-4 WINEDLLOVERRIDES="dinput8.dll=n,b" umu-run /home/user/Games/umu/umu-ELDENRING/drive_c/Games/'ELDEN RING'/Game/eldenring.exe
> 
> You should be able to use this line, you can drop WINEDLLOVERRIDES and prefix the umu-run with `bash elden-proton.bash`

Ok, thanks again.
