### ISSUE TITLE
dinput8.dll preventing online play

### ISSUE THREAD

**Issue by VisibleSampling** [Cloudef/elden-proton#13]
When `dinput8.dll` is present inside of the `$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/` directory EAC will initialize but the game will exit afterwards. I have tried this with a clean install of both the game and `elden-proton`.

By renaming the dll to `dinput8.dll.old` the game launches in online mode without issue. I believe that Fromsoft has changed some of its cheat detection, specifically with Linux and it makes things more fragile. 

For a quick and dirty solution you could  rename the DLL
```
"Disable Mods")
    printf 0 > "$ER_PATH"/EldenProton/state
    # Rename dinput8.dll to dinput8.dll.old if it exists
    if [[ -f "$ER_PATH/dinput8.dll" ]]; then
        mv "$ER_PATH/dinput8.dll" "$ER_PATH/dinput8.dll.old"
    fi
    ;;
```

```
"Enable Mods")
    printf 1 > "$ER_PATH"/EldenProton/state
    # Rename dinput8.dll.old back to dinput8.dll if it exists
    if [[ -f "$ER_PATH/dinput8.dll.old" ]]; then
        mv "$ER_PATH/dinput8.dll.old" "$ER_PATH/dinput8.dll"
    fi
    ;;
 ```

**Comment by Cloudef** [comment]
That might be good idea in any case
