### ISSUE TITLE
[Help] Required files failed to download (curl not in PATH when run from steam)

### ISSUE THREAD

**Issue by KrisCris** [Cloudef/elden-proton#5]
I am not sure what was wrong or which file failed to download, but I got this error immediately after I launched the game.

My internet is fine, I was able to manually download files from both nexusmods and github.

**Comment by Cloudef** [comment]
Do you get integrity check fails?

**Comment by KrisCris** [comment]
The integrity of my game files is fine, if this is what you are referring to.

For the files downloaded by elden-proton, I am not sure.

**Comment by Cloudef** [comment]
I mean the elden-proton should show dialog if integrity check of downloaded files fail. Though I just tested myself and the downloads seem ok. So some command is failing.

Can you run the script like this from terminal `bash -x elden-proton.bash true` 
Post the output then

**Comment by Cloudef** [comment]
I also updated the script for more error messages.

**Comment by KrisCris** [comment]
> I mean the elden-proton should show dialog if integrity check of downloaded files fail.

No, it just showed **Required files failed to download**, I don't think anything was downloaded at that moment, cuz it failed immediately.

> Can you run the script like this from terminal `bash -x elden-proton.bash` true

This command worked for me, required files are downloaded without issue. Now I can launch the game from Steam.

**Comment by Cloudef** [comment]
So it only fails when run through game mode / steam? or is this non steam deck, are you using flatpak for steam?

**Comment by KrisCris** [comment]
Yeah, I just tried one more time, it only fails when running from Steam. I am on Steam Deck desktop mode.

**Comment by KrisCris** [comment]
Ah, I just pulled the latest update, now it's saying "Executing curl failed... Do you have curl Installed"

**Comment by Cloudef** [comment]
Interesting. I unfortunately don't have a deck. But it seems curl is not in PATH when run from steam.
https://github.com/Cloudef/elden-proton/issues/4 does this same workaround work perhaps?

**Comment by KrisCris** [comment]
Yea, I just realized that after looking into the code

> https://github.com/Cloudef/elden-proton/issues/4 does this same workaround work perhaps?

~~Yes, this fixed it.~~

Edit: This fixed it when launching the game from desktop mode, however, it refuses to run when in the game mode (gamescope?).  

I guess I will use `bash -x elden-proton.bash` as a workaround for now lol

**Comment by Cloudef** [comment]
Not sure why bash -x would fix it :confused:

**Comment by KrisCris** [comment]
I mean by running it directly from the terminal, where it can get the curl

**Comment by Cloudef** [comment]
Ah right. When you run that under steam be it desktop or gamemode, the steam runtime may affect things.

**Comment by Cloudef** [comment]
Did you make sure `LD_LIBRARY_PATH= ` was also in launch options when running from gamemode?

**Comment by KrisCris** [comment]
> Did you make sure `LD_LIBRARY_PATH= ` was also in launch options when running from gamemode?

Yes, but when it appears in launch option in the gamemode, the game refuses to run. Some command failed I guess.

**Comment by Cloudef** [comment]
Ah right, that's because it also affects proton. I'll try put in a fix that probably works.

**Comment by Cloudef** [comment]
Pushed update. Please test

**Comment by KrisCris** [comment]
Thanks, it now works great!
